-   id: file-permission-checker
    name: File Permission Check
    description: Prevents text files from being commited as executables.
    entry: check-file-permissions
    language: python
    types: [text]
